sonar.projectKey=EduControlG3
sonar.projectName=EduControl G3
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,public/**,database/**,docs/**,.env,package-lock.json
